### ISSUE TITLE
[Suggestion] Add a configurable time before an offline player stops adding to factions power

### ISSUE THREAD

**Issue by Josh65-2201** [ToberoCat/ImprovedFactions_new#104]
**Is your feature request related to a problem? Please describe.**
The current issue is that factions will lose all the power and go into the negative when they are sleeping which is unfair especially with multi time zone players in one faction compared to a single player.

**Describe the solution you'd like**
Add a config option for time allowed offline default to 24 hours. The database can save the exit date and time of the user and when it's past the config time that player will stop giving power.

**Comment by ToberoCat** [comment]
This is already configurable. 

```yml
    # Configure how long a player counts as active.
    inactive:
      unit: DAYS # The time unit this value will be interpreted as. Some more common possibilities are: SECONDS, MINUTES, HOURS and DAYS
      value: 7
```

These are the default values for it. They will make sure that players only count as inactive if they are:
- Not online
- Haven't been on the server for at least 7 days


I'll leave this issue open, maybe I missed something
